#!/bin/sh
set -e

#DEBHELPER#

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ]; then
    if ls /usr/lib/meshlab/*.AppImage >/dev/null 2>&1; then
        chmod +x /usr/lib/meshlab/*.AppImage || true
    fi

    if [ -x /usr/bin/update-desktop-database ]; then
        update-desktop-database -q /usr/share/applications || true
    fi
fi

exit 0
