#!/bin/bash
# postinst script for vx-dga-l-meshlab
set -e

case "$1" in
    configure)
        APPIMAGE="/usr/share/vitalinux/appimages/MeshLab2025.07-linux_x86_64.AppImage"
        BINARIO="/usr/bin/vx-meshlab"

        if [ -f "${APPIMAGE}" ]; then
            chmod +x "${APPIMAGE}"
            ln -sf "${APPIMAGE}" "${BINARIO}" || echo "No se puede crear el enlace al binario..."
        else
            echo "Hubo un error con la APP..."
        fi
    ;;
    abort-upgrade | abort-remove | abort-deconfigure) ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
